server:
  port: 8806
  servlet:
    context-path: /quant-stock-list

# DataSource Config
spring:
  application:
    name: quant-stock-list
  profiles:
    active: dev
  cloud:
    nacos:
      #nacos服务端地址及端口
      server-addr: 127.0.0.1:7000
      #登录页面账号和密码
      username: nacos
      password: nacos
      config:
        #nacos可以以命名空间作为不同环境依据(默认dev)
        namespace: ${spring.profiles.active:dev}
        group: quant-stock-list
      discovery:
        namespace: ${spring.profiles.active:dev}
    sentinel:
      transport:
        dashboard: localhost:7003
      #默认懒加载机制,也就是说有第一次的流量访问之后才会,这里显示指定直接连接就显示在控制台
      eager: true
  config:
    import:
      - nacos:application-dev.yml
